server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

api:
  sports:
    base-url: https://v3.football.api-sports.io
    key: eeb82da4384bf7352f346c9371fe3dad
