import os

# Definitions of translated key-value pairs for each language
translations = {
    # German (de)
    "de": {
        "app_name": "LiveScore Premium",
        "nav_live": "Live",
        "nav_news": "News",
        "nav_favorite": "Favoriten",
        "nav_profile": "Profil",
        "wc26": "WM 26",
        "favorite_title": "FAVORITEN",
        "my_follow": "DEINE FAVORITEN",
        "my_matches": "DEINE SPIELE",
        "live": "LIVE",
        "upcoming": "BEVORSTEHEND",
        "finished": "BEENDET",
        "empty_matches": "Noch keine Lieblingsspiele",
        "empty_leagues": "Noch keine Lieblingsligen",
        "empty_teams": "Noch keine Lieblingsteams",
        "empty_players": "Noch keine Lieblingsspieler",
        "profile_title": "MEIN PROFIL",
        "language": "Sprache",
        "premium_badge": "👑 PREMIUM-MITGLIED",
        "free_plan": "GRATIS-VERSION",
        "daily_limit": "Tägliches API-Limit",
        "upgrade_button": "JETZT UPGRADEN",
        "intro_next": "Weiter",
        "intro_start": "Start",
        "intro_step_1_progress": "Schritt 1: 1/3",
        "intro_step_2_progress": "Schritt 2: 2/3",
        "intro_step_3_progress": "Schritt 3: 3/3",
        "intro_step_1_title": "LIEBLINGSLIGEN WÄHLEN",
        "intro_step_1_subtitle": "Filtere News & Ergebnisse deiner Ligen",
        "intro_step_1_hint": "Ligen suchen...",
        "intro_step_2_title": "TEAMS WÄHLEN",
        "intro_step_2_subtitle": "Deine Lieblingsteams werden zuerst angezeigt",
        "intro_step_2_hint": "Teams, Clubs suchen...",
        "intro_step_3_title": "SPIELER WÄHLEN",
        "intro_step_3_subtitle": "Folge den besten Fußball-Superstars der Welt",
        "intro_step_3_hint": "Spieler suchen...",
        "intro_finish": "FERTIG",
        "item_hot": " • Beliebt 🔥",
        "item_belongs": "Gehört zu: %1$s",
        "item_nationality": "Nationalität: %1$s",
        "intro_skip": "ÜBERSPRINGEN",
        "intro_no_results": "Keine Ergebnisse gefunden",
        "welcome_title": "WILLKOMMEN BEI LIVESCORE",
        "choose_language": "SPRACHE WÄHLEN",
        "choose_language_desc": "Wähle die offizielle Anzeigesprache der App, um fortzufahren.",
        "profile_settings": "EINSTELLUNGEN",
        "profile_display_preferences": "DESIGN & PERSONALISIERUNG",
        "profile_system": "SPEICHER & SYSTEM",
        "profile_about": "SOFTWARE-INFO",
        "profile_version": "Version",
        "language_dialog_title": "Sprache wählen",
        "language_changed_toast": "Sprache geändert auf %1$s",
        "splash_app_title": "LIVESCORE",
        "splash_subtitle": "PREMIUM-SPORTZENTRUM",
        "tab_matches": "SPIELE",
        "tab_leagues": "LIGEN",
        "empty_fixtures": "Keine Spiele gefunden",
        "tab_standings": "TABELLE",
        "tab_fixtures": "SPIELE",
        "table_header_team": "TEAM",
        "table_header_p": "SP",
        "table_header_w": "S",
        "table_header_d": "U",
        "table_header_l": "N",
        "table_header_gd": "TD",
        "table_header_pts": "PKT",
        "tab_stats": "STATS",
        "tab_timeline": "VERLAUF",
        "tab_lineups": "AUFSTELLUNG",
        "search_input_hint": "Spiele, Teams, Ligen suchen...",
        "search_empty_title": "Fußball entdecken",
        "search_empty_desc": "Suche nach Top-Teams und Ligen wie Premier League, Real Madrid, Vietnam oder WM 2026...",
        "news_center_title": "NEWS 24H",
        "news_featured_today": "⭐ HEUTE IM FOKUS",
        "news_1_title": "FIFA gibt offiziell den Spielplan für die WM 2026 in den USA, Mexiko und Kanada bekannt!",
        "news_1_desc": "Das historische Eröffnungsspiel findet im berühmten Aztekenstadion in Mexiko statt. New York/New Jersey hat das Finale erhalten.",
        "news_1_author": "Von der Redaktion • 5 Min. Lesezeit",
        "news_detail_link": "Details ➔",
        "news_2_title": "Arsenal dominiert Chelsea mit 5:0 im Emirates und macht spektakulären Sprung in der Tabelle",
        "news_2_desc": "Doppelpacks von Ben White und Kai Havertz halfen den Gunners, den Stadtrivalen zu besiegen und ein Zeichen an Man City zu senden...",
        "news_2_time": "Vor 1 Std. • 3 Min. Lesezeit",
        "news_3_title": "Kylian Mbappé stimmt vorläufigen Bedingungen für Wechsel zu Real Madrid zu",
        "news_3_desc": "Alle persönlichen Bedingungen wurden vereinbart. Der französische Superstar wechselt ablösefrei und mit Rekordprämie zu Real...",
        "news_3_time": "Vor 3 Std. • 4 Min. Lesezeit",
        "news_4_title": "Wahnsinn im Halbfinale: Real Madrid schafft Wunder-Comeback gegen Bayern München",
        "news_4_desc": "Zwei späte Tore von Joselu in der Nachspielzeit ließen das Bernabéu explodieren und schickten Real Madrid ins Finale...",
        "news_4_time": "Gestern • 6 Min. Lesezeit",
        "wc26_days_until": "Noch %1$d Tage bis zur Eröffnungsfeier",
        "wc26_starts_today": "⚽ ANSTOSS HEUTE!",
        "wc26_ongoing": "⚽ WM 2026 läuft bereits!",
        "wc26_groups": "GRUPPEN",
        "wc26_teams": "TEAMS",
        "wc26_news": "NEWS",
        "wc26_opening_match": "Eröffnungsspiel • Runde 1",
        "wc26_azteca_stadium": "Aztekenstadion, Mexiko-Stadt",
        "wc26_metlife_stadium": "MetLife Stadium, New York",
        "wc26_vs": "vs",
        "wc26_round_1_group_a": "Runde 1 • Gruppe A",
        "wc26_group_a": "GRUPPE A",
        "wc26_group_b": "GRUPPE B",
        "wc26_qualified_teams": "QUALIFIZIERTE TEAMS",
        "wc26_exclusive_news": "EXKLUSIV",
        "wc26_exclusive_news_title": "Das WM-Finale 2026 findet prachtvoll in New York/New Jersey statt!",
        "wc26_exclusive_news_desc": "Die FIFA hat die Austragungsrechte für das Finale offiziell an das MetLife Stadium mit über 82.500 Plätzen am 19. Juli 2026 vergeben.",
        "wc26_preparation": "VORBEREITUNG",
        "wc26_prep_title": "USA beschleunigen Verkehrs- und Sicherheitsinfrastruktur für Rekordbesucherzahlen",
        "wc26_prep_desc": "Die Bundesregierung hat ein Sonderbudget genehmigt, um U-Bahnen und Flugverkehr direkt zu den Austragungsorten zu modernisieren...",
        "wc26_view_now": "JETZT ANSEHEN ➔",
        "wc26_general_news": "📰 ALLGEMEINE NEWS",
        "wc26_general_news_desc": "Sieh dir alle Sportereignisse, Transfers & Ligen-News der letzten 24 Stunden an",
        "league_center_title": "LIGA-CENTER",
        "league_center_subtitle": "Globale Tabellen & Statistiken",
        "tab_scorers": "TORSCHÜTZEN",
        "tab_assists": "VORLAGEN",
        "share_title": "SPIEL TEILEN",
        "share_score_title": "Spielstand &amp; Status",
        "share_score_desc": "Teile Echtzeittore und den Spielstatus.",
        "share_stats_title": "Detaillierte Spielstatistiken",
        "share_stats_desc": "Teile Ballbesitz, Schüsse und Ecken.",
        "share_full_title": "Vollständiger Spielbericht",
        "share_full_desc": "Teile den gesamten Bericht mit Toren und Statistiken.",
        "share_via": "Teilen über",
        "share_copied_toast": "In die Zwischenablage kopiert!",
        "reminder_set_toast": "Erinnerung für das Spiel aktiviert!",
        "reminder_cancelled_toast": "Erinnerung für das Spiel deaktiviert!",
        "share_caption_template": "Sieh dir die Spielstatistiken für %1$s gegen %2$s bei livescore://match/%3$d an (App herunterladen: https://livescore.premium/download)"
    },
    
    # Spanish (es)
    "es": {
        "app_name": "LiveScore Premium",
        "nav_live": "En vivo",
        "nav_news": "Noticias",
        "nav_favorite": "Favoritos",
        "nav_profile": "Perfil",
        "wc26": "Mundial 26",
        "favorite_title": "FAVORITOS",
        "my_follow": "TUS SEGUIMIENTOS",
        "my_matches": "TUS PARTIDOS",
        "live": "EN VIVO",
        "upcoming": "PRÓXIMOS",
        "finished": "FINALIZADOS",
        "empty_matches": "No hay partidos favoritos aún",
        "empty_leagues": "No hay ligas favoritas aún",
        "empty_teams": "No hay equipos favoritos aún",
        "empty_players": "No hay jugadores favoritos aún",
        "profile_title": "MI PERFIL",
        "language": "Idioma",
        "premium_badge": "👑 MIEMBRO PREMIUM",
        "free_plan": "PLAN GRATUITO",
        "daily_limit": "Límite de uso diario de API",
        "upgrade_button": "MEJORAR AHORA",
        "intro_next": "Siguiente",
        "intro_start": "Empezar",
        "intro_step_1_progress": "Paso 1: 1/3",
        "intro_step_2_progress": "Paso 2: 2/3",
        "intro_step_3_progress": "Paso 3: 3/3",
        "intro_step_1_title": "SELECCIONAR LIGAS FAVORITAS",
        "intro_step_1_subtitle": "Filtra noticias y resultados de las ligas que te interesan",
        "intro_step_1_hint": "Buscar ligas...",
        "intro_step_2_title": "SELECCIONAR EQUIPOS QUE SIGUES",
        "intro_step_2_subtitle": "Priorizaremos mostrar primero los clubes que selecciones",
        "intro_step_2_hint": "Buscar equipos, clubes...",
        "intro_step_3_title": "SELECCIONAR JUGADORES FAVORITOS",
        "intro_step_3_subtitle": "Sigue a las superestrellas del fútbol mundial",
        "intro_step_3_hint": "Buscar jugadores...",
        "intro_finish": "FINALIZAR",
        "item_hot": " • Popular 🔥",
        "item_belongs": "Pertenece a: %1$s",
        "item_nationality": "Nacionalidad: %1$s",
        "intro_skip": "OMITIR",
        "intro_no_results": "No se encontraron resultados",
        "welcome_title": "BIENVENIDO A LIVESCORE",
        "choose_language": "SELECCIONAR IDIOMA",
        "choose_language_desc": "Selecciona el idioma oficial de la aplicación para continuar.",
        "profile_settings": "CONFIGURACIÓN",
        "profile_display_preferences": "DISEÑO & PERSONALIZACIÓN",
        "profile_system": "ALMACENAMIENTO & SISTEMA",
        "profile_about": "INFORMACIÓN DE SOFTWARE",
        "profile_version": "Versión",
        "language_dialog_title": "Seleccionar idioma",
        "language_changed_toast": "Idioma actualizado a %1$s",
        "splash_app_title": "LIVESCORE",
        "splash_subtitle": "CENTRO DE DEPORTES PREMIUM",
        "tab_matches": "PARTIDOS",
        "tab_leagues": "LIGAS",
        "empty_fixtures": "No se encontraron partidos",
        "tab_standings": "CLASIFICACIÓN",
        "tab_fixtures": "PARTIDOS",
        "table_header_team": "EQUIPO",
        "table_header_p": "PJ",
        "table_header_w": "PG",
        "table_header_d": "PE",
        "table_header_l": "PP",
        "table_header_gd": "DG",
        "table_header_pts": "PTS",
        "tab_stats": "ESTADÍSTICAS",
        "tab_timeline": "CRONOLOGÍA",
        "tab_lineups": "ALINEACIONES",
        "search_input_hint": "Buscar partidos, equipos, ligas...",
        "search_empty_title": "Explorar fútbol",
        "search_empty_desc": "Busca equipos y ligas top como Premier League, Real Madrid, Vietnam o el Mundial 2026...",
        "news_center_title": "NOTICIAS 24H",
        "news_featured_today": "⭐ DESTACADO HOY",
        "news_1_title": "¡FIFA anuncia oficialmente el calendario de partidos de la Copa Mundial 2026 en EE. UU., México y Canadá!",
        "news_1_desc": "El histórico partido inaugural se jugará en el famoso Estadio Azteca de México. Nueva York/Nueva Jersey se quedó con la final.",
        "news_1_author": "Por la redacción • 5 min de lectura",
        "news_detail_link": "Detalles ➔",
        "news_2_title": "Arsenal domina a Chelsea 5-0 en el Emirates y hace un salto espectacular en la tabla",
        "news_2_desc": "Los dobletes de Ben White y Kai Havertz ayudaron a los Gunners a hundir a sus rivales y mandar un mensaje a Man City...",
        "news_2_time": "Hace 1 hora • 3 min de lectura",
        "news_3_title": "Kylian Mbappé acuerda términos preliminares para unirse al Real Madrid",
        "news_3_desc": "Todos los términos personales están acordados. La superestrella francesa llegará al Bernabéu libre con una prima de fichaje récord...",
        "news_3_time": "Hace 3 horas • 4 min de lectura",
        "news_4_title": "Escenario loco en Semifinales: Real Madrid logra remontada milagrosa contra Bayern Múnich",
        "news_4_desc": "Dos goles tardíos de Joselu en el tiempo de descuento encendieron el Bernabéu, enviando al Real Madrid a la final...",
        "news_4_time": "Ayer • 6 min de lectura",
        "wc26_days_until": "Quedan %1$d días para la ceremonia de apertura",
        "wc26_starts_today": "⚽ ¡EL INICIO ES HOY!",
        "wc26_ongoing": "⚽ ¡El Mundial 2026 ya está en marcha!",
        "wc26_groups": "GRUPOS",
        "wc26_teams": "EQUIPOS",
        "wc26_news": "NOTICIAS",
        "wc26_opening_match": "Partido Inaugural • Jornada 1",
        "wc26_azteca_stadium": "Estadio Azteca, Ciudad de México",
        "wc26_metlife_stadium": "Estadio MetLife, Nueva York",
        "wc26_vs": "vs",
        "wc26_round_1_group_a": "Jornada 1 • Grupo A",
        "wc26_group_a": "GRUPO A",
        "wc26_group_b": "GRUPO B",
        "wc26_qualified_teams": "EQUIPOS CLASIFICADOS",
        "wc26_exclusive_news": "EXCLUSIVA",
        "wc26_exclusive_news_title": "¡La final del Mundial 2026 se celebrará a lo grande en Nueva York/Nueva Jersey!",
        "wc26_exclusive_news_desc": "La FIFA otorgó oficialmente los derechos para la final al MetLife Stadium con capacidad para más de 82,500 personas el 19 de julio de 2026.",
        "wc26_preparation": "PREPARACIÓN",
        "wc26_prep_title": "EE. UU. acelera transporte e infraestructura de seguridad para número récord de fans",
        "wc26_prep_desc": "El gobierno federal aprobó un presupuesto especial para mejorar subterráneos y aviación que conectan las ciudades sede...",
        "wc26_view_now": "VER AHORA ➔",
        "wc26_general_news": "📰 NOTICIAS GENERALES",
        "wc26_general_news_desc": "Ver eventos deportivos, transferencias y noticias de las ligas en las últimas 24 horas",
        "league_center_title": "CENTRO DE LIGAS",
        "league_center_subtitle": "Clasificaciones y estadísticas globales",
        "tab_scorers": "GOLEADORES",
        "tab_assists": "ASISTENCIAS",
        "share_title": "COMPARTIR PARTIDO",
        "share_score_title": "Resultado y Estado",
        "share_score_desc": "Comparte goles en tiempo real y el estado del partido.",
        "share_stats_title": "Estadísticas Detalladas",
        "share_stats_desc": "Comparte posesión, tiros y córneres.",
        "share_full_title": "Informe Completo del Partido",
        "share_full_desc": "Comparte el informe completo combinando goles y estadísticas.",
        "share_via": "Compartir vía",
        "share_copied_toast": "¡Copiado al portapapeles!",
        "reminder_set_toast": "¡Recordatorio activado para el partido!",
        "reminder_cancelled_toast": "¡Recordatorio desactivado para el partido!",
        "share_caption_template": "¡Consulta las estadísticas del partido %1$s vs %2$s en livescore://match/%3$d (Descarga la app: https://livescore.premium/download)!"
    },
    
    # Portuguese (pt)
    "pt": {
        "app_name": "LiveScore Premium",
        "nav_live": "Ao vivo",
        "nav_news": "Notícias",
        "nav_favorite": "Favoritos",
        "nav_profile": "Perfil",
        "wc26": "Mundial 26",
        "favorite_title": "FAVORITOS",
        "my_follow": "SEUS SEGUIDOS",
        "my_matches": "SEUS JOGOS",
        "live": "AO VIVO",
        "upcoming": "PRÓXIMOS",
        "finished": "TERMINADOS",
        "empty_matches": "Nenhum jogo favorito ainda",
        "empty_leagues": "Nenhuma liga favorita ainda",
        "empty_teams": "Nenhuma equipe favorita ainda",
        "empty_players": "Nenhum jogador favorito ainda",
        "profile_title": "MEU PERFIL",
        "language": "Idioma",
        "premium_badge": "👑 MEMBRO PREMIUM",
        "free_plan": "PLANO GRATUITO",
        "daily_limit": "Limite de uso diário da API",
        "upgrade_button": "UPGRADE AGORA",
        "intro_next": "Próximo",
        "intro_start": "Começar",
        "intro_step_1_progress": "Passo 1: 1/3",
        "intro_step_2_progress": "Passo 2: 2/3",
        "intro_step_3_progress": "Passo 3: 3/3",
        "intro_step_1_title": "SELECIONAR LIGAS FAVORITAS",
        "intro_step_1_subtitle": "Filtre notícias e resultados das ligas do seu interesse",
        "intro_step_1_hint": "Buscar ligas...",
        "intro_step_2_title": "SELECIONAR EQUIPES QUE SEGUE",
        "intro_step_2_subtitle": "Daremos prioridade para mostrar os clubes que selecionar",
        "intro_step_2_hint": "Buscar equipes, clubes...",
        "intro_step_3_title": "SELECIONAR JOGADORES FAVORITOS",
        "intro_step_3_subtitle": "Siga as superestrelas do futebol mundial",
        "intro_step_3_hint": "Buscar jogadores...",
        "intro_finish": "FINALIZAR",
        "item_hot": " • Popular 🔥",
        "item_belongs": "Pertence a: %1$s",
        "item_nationality": "Nacionalidade: %1$s",
        "intro_skip": "IGNORAR",
        "intro_no_results": "Nenhum resultado encontrado",
        "welcome_title": "BEM-VINDO AO LIVESCORE",
        "choose_language": "SELECIONAR IDIOMA",
        "choose_language_desc": "Selecione o idioma de exibição oficial para continuar.",
        "profile_settings": "CONFIGURAÇÕES",
        "profile_display_preferences": "VISUAL & PERSONALIZAÇÃO",
        "profile_system": "ARMAZENAMENTO & SISTEMA",
        "profile_about": "INFORMAÇÃO DO SOFTWARE",
        "profile_version": "Versão",
        "language_dialog_title": "Selecionar idioma",
        "language_changed_toast": "Idioma atualizado para %1$s",
        "splash_app_title": "LIVESCORE",
        "splash_subtitle": "CENTRO DE ESPORTES PREMIUM",
        "tab_matches": "JOGOS",
        "tab_leagues": "LIGAS",
        "empty_fixtures": "Nenhum jogo encontrado",
        "tab_standings": "TABELA",
        "tab_fixtures": "JOGOS",
        "table_header_team": "EQUIPE",
        "table_header_p": "J",
        "table_header_w": "V",
        "table_header_d": "E",
        "table_header_l": "D",
        "table_header_gd": "SG",
        "table_header_pts": "PTS",
        "tab_stats": "ESTATÍSTICAS",
        "tab_timeline": "LINHA DO TEMPO",
        "tab_lineups": "ESCALAÇÕES",
        "search_input_hint": "Buscar jogos, equipes, ligas...",
        "search_empty_title": "Explorar futebol",
        "search_empty_desc": "Busque equipes e ligas como Premier League, Real Madrid, Vietnã ou a Copa do Mundo 2026...",
        "news_center_title": "NOTÍCIAS 24H",
        "news_featured_today": "⭐ DESTAQUE DE HOJE",
        "news_1_title": "FIFA anuncia oficialmente o calendário de jogos da Copa do Mundo 2026 nos EUA, México e Canadá!",
        "news_1_desc": "O histórico jogo de abertura será no famoso Estádio Azteca, no México. Nova York/Nova Jersey sediará a grande final.",
        "news_1_author": "Pela redação • 5 min de leitura",
        "news_detail_link": "Detalhes ➔",
        "news_2_title": "Arsenal domina o Chelsea por 5-0 no Emirates e dá salto espetacular na tabela",
        "news_2_desc": "As dobradinhas de Ben White e Kai Havertz ajudaram os Gunners a afundar os rivais da cidade e enviar uma mensagem ao Man City...",
        "news_2_time": "Há 1 hora • 3 min de leitura",
        "news_3_title": "Kylian Mbappé aceita termos preliminares para se juntar ao Real Madrid",
        "news_3_desc": "Todos os termos pessoais estão acordados. A superestrela francesa chegará ao Bernabéu livre com um bônus de assinatura recorde...",
        "news_3_time": "Há 3 horas • 4 min de leitura",
        "news_4_title": "Cenário louco nas semifinais: Real Madrid faz virada milagrosa contra o Bayern de Munique",
        "news_4_desc": "Dois gols tardios de Joselu nos acréscimos incendiaram o Bernabéu, enviando o Real Madrid para a final...",
        "news_4_time": "Ontem • 6 min de leitura",
        "wc26_days_until": "Restam %1$d dias para a cerimônia de abertura",
        "wc26_starts_today": "⚽ O PONTAPÉ INICIAL É HOJE!",
        "wc26_ongoing": "⚽ A Copa do Mundo 2026 já começou!",
        "wc26_groups": "GRUPOS",
        "wc26_teams": "EQUIPES",
        "wc26_news": "NOTÍCIAS",
        "wc26_opening_match": "Jogo de Abertura • Rodada 1",
        "wc26_azteca_stadium": "Estádio Azteca, Cidade do México",
        "wc26_metlife_stadium": "Estádio MetLife, Nova York",
        "wc26_vs": "vs",
        "wc26_round_1_group_a": "Rodada 1 • Grupo A",
        "wc26_group_a": "GRUPO A",
        "wc26_group_b": "GRUPO B",
        "wc26_qualified_teams": "EQUIPES CLASSIFICADAS",
        "wc26_exclusive_news": "EXCLUSIVA",
        "wc26_exclusive_news_title": "A final da Copa 2026 será celebrada em grande estilo em Nova York/Nova Jersey!",
        "wc26_exclusive_news_desc": "A FIFA concedeu oficialmente os direitos de sede para a final ao MetLife Stadium com capacidade para mais de 82.500 pessoas em 19 de julho de 2026.",
        "wc26_preparation": "PREPARAÇÃO",
        "wc26_prep_title": "EUA aceleram transporte e infraestrutura de segurança para número recorde de fãs",
        "wc26_prep_desc": "O governo federal aprovou um orçamento especial para atualizar metrôs e aviação conectando diretamente as cidades sede...",
        "wc26_view_now": "VER AGORA ➔",
        "wc26_general_news": "📰 NOTÍCIAS GERAIS",
        "wc26_general_news_desc": "Ver eventos esportivos, transferências e notícias das ligas nas últimas 24 horas",
        "league_center_title": "CENTRO DE LIGAS",
        "league_center_subtitle": "Classificações e estatísticas globais",
        "tab_scorers": "ARTILHEIROS",
        "tab_assists": "ASSISTÊNCIAS",
        "share_title": "COMPARTILHAR JOGO",
        "share_score_title": "Placar e Status",
        "share_score_desc": "Compartilhe gols em tempo real e o status do jogo.",
        "share_stats_title": "Estatísticas Detalhadas",
        "share_stats_desc": "Compartilhe posse, chutes e escanteios.",
        "share_full_title": "Relatório Completo do Jogo",
        "share_full_desc": "Compartilhe o relatório completo combinando placar e estatísticas.",
        "share_via": "Compartilhar via",
        "share_copied_toast": "Copiado para a área de transferência!",
        "reminder_set_toast": "Lembrete ativado para a partida!",
        "reminder_cancelled_toast": "Lembrete desativado para a partida!",
        "share_caption_template": "Confira as estatísticas do jogo %1$s vs %2$s em livescore://match/%3$d (Baixe o app: https://livescore.premium/download)"
    },
    
    # Italian (it)
    "it": {
        "app_name": "LiveScore Premium",
        "nav_live": "Dal vivo",
        "nav_news": "Notizie",
        "nav_favorite": "Preferiti",
        "nav_profile": "Profilo",
        "wc26": "Mondiale 26",
        "favorite_title": "PREFERITI",
        "my_follow": "I TUOI SEGUITI",
        "my_matches": "I TUOI INCONTRI",
        "live": "DAL VIVO",
        "upcoming": "PROSSIMI",
        "finished": "TERMINATI",
        "empty_matches": "Nessuna partita preferita",
        "empty_leagues": "Nessuna lega preferita",
        "empty_teams": "Nessuna squadra preferita",
        "empty_players": "Nessun giocatore preferito",
        "profile_title": "IL MIO PROFILO",
        "language": "Lingua",
        "premium_badge": "👑 MEMBRO PREMIUM",
        "free_plan": "PIANO GRATUITO",
        "daily_limit": "Limite di utilizzo giornaliero dell\'API",
        "upgrade_button": "ABBONATI ORA",
        "intro_next": "Avanti",
        "intro_start": "Avvia",
        "intro_step_1_progress": "Passo 1: 1/3",
        "intro_step_2_progress": "Passo 2: 2/3",
        "intro_step_3_progress": "Passo 3: 3/3",
        "intro_step_1_title": "SELEZIONA LE LEGHE PREFERITE",
        "intro_step_1_subtitle": "Filtra notizie e risultati delle leghe che ti interessano",
        "intro_step_1_hint": "Cerca leghe...",
        "intro_step_2_title": "SELEZIONA LE SQUADRE CHE SEGUI",
        "intro_step_2_subtitle": "Daremo la priorità ai club che selezioni",
        "intro_step_2_hint": "Cerca squadre, club...",
        "intro_step_3_title": "SELEZIONA I GIOCATORI PREFERITI",
        "intro_step_3_subtitle": "Segui le superstelle del calcio mondiale",
        "intro_step_3_hint": "Cerca giocatori...",
        "intro_finish": "FINE",
        "item_hot": " • Popolare 🔥",
        "item_belongs": "Appartiene a: %1$s",
        "item_nationality": "Nazionalità: %1$s",
        "intro_skip": "SALTA",
        "intro_no_results": "Nessun risultato trovato",
        "welcome_title": "BENVENUTO SU LIVESCORE",
        "choose_language": "SELEZIONA LA LINGUA",
        "choose_language_desc": "Seleziona la lingua ufficiale dell\'applicazione per continuare.",
        "profile_settings": "IMPOSTAZIONI",
        "profile_display_preferences": "DESIGN & PERSONALIZZAZIONE",
        "profile_system": "MEMORIA & SISTEMA",
        "profile_about": "INFORMAZIONI SUL SOFTWARE",
        "profile_version": "Versione",
        "language_dialog_title": "Seleziona lingua",
        "language_changed_toast": "Lingua aggiornata a %1$s",
        "splash_app_title": "LIVESCORE",
        "splash_subtitle": "CENTRO SPORTIVO PREMIUM",
        "tab_matches": "INCONTRI",
        "tab_leagues": "LEGHE",
        "empty_fixtures": "Nessun incontro trovato",
        "tab_standings": "CLASSIFICA",
        "tab_fixtures": "INCONTRI",
        "table_header_team": "SQUADRA",
        "table_header_p": "G",
        "table_header_w": "V",
        "table_header_d": "N",
        "table_header_l": "P",
        "table_header_gd": "DR",
        "table_header_pts": "PT",
        "tab_stats": "STATISTICHE",
        "tab_timeline": "CRONOLOGIA",
        "tab_lineups": "FORMAZIONI",
        "search_input_hint": "Cerca incontri, squadre, leghe...",
        "search_empty_title": "Esplora il calcio",
        "search_empty_desc": "Cerca squadre e leghe top come Premier League, Real Madrid, Vietnam o la Coppa del Mondo 2026...",
        "news_center_title": "NOTIZIE 24H",
        "news_featured_today": "⭐ IN EVIDENZA OGGI",
        "news_1_title": "La FIFA annuncia ufficialmente il calendario delle partite della Coppa del Mondo 2026 negli USA, in Messico e in Canada!",
        "news_1_desc": "La storica partita inaugurale si giocherà nel famoso stadio Azteca in Messico. New York/New Jersey ospiterà la finale.",
        "news_1_author": "Dalla redazione • 5 min di lettura",
        "news_detail_link": "Dettagli ➔",
        "news_2_title": "L\'Arsenal domina il Chelsea 5-0 all\'Emirates e fa un balzo spettacolare in classifica",
        "news_2_desc": "Le doppiette di Ben White e Kai Havertz aiutano i Gunners ad affondare i rivali cittadini e inviano un segnale al Man City...",
        "news_2_time": "1 ora fa • 3 min di lettura",
        "news_3_title": "Kylian Mbappé accetta i termini preliminari per unirsi al Real Madrid",
        "news_3_desc": "Tutti i termini personali sono concordati. La stella francese arriverà al Bernabéu a parametro zero con un bonus record...",
        "news_3_time": "3 ore fa • 4 min di lettura",
        "news_4_title": "Scenario pazzesco alle semifinali: il Real Madrid compie una rimonta miracolosa contro il Bayern Monaco",
        "news_4_desc": "Due gol nel finale di recupero di Joselu infiammano il Bernabéu, mandando il Real Madrid in finale...",
        "news_4_time": "Ieri • 6 min di lettura",
        "wc26_days_until": "Mancano %1$d giorni alla cerimonia d\'apertura",
        "wc26_starts_today": "⚽ IL CALCIO D\'INIZIO È OGGI!",
        "wc26_ongoing": "⚽ La Coppa del Mondo 2026 è iniziata!",
        "wc26_groups": "GRUPPI",
        "wc26_teams": "SQUADRE",
        "wc26_news": "NEWS",
        "wc26_opening_match": "Partita Inaugurale • Giornata 1",
        "wc26_azteca_stadium": "Stadio Azteca, Città del Messico",
        "wc26_metlife_stadium": "Stadio MetLife, New York",
        "wc26_vs": "vs",
        "wc26_round_1_group_a": "Giornata 1 • Gruppo A",
        "wc26_group_a": "GRUPPO A",
        "wc26_group_b": "GRUPPO B",
        "wc26_qualified_teams": "SQUADRE QUALIFICATE",
        "wc26_exclusive_news": "ESCLUSIVA",
        "wc26_exclusive_news_title": "La finale della Coppa 2026 sarà celebrata alla grande a New York/New Jersey!",
        "wc26_exclusive_news_desc": "La FIFA ha assegnato ufficialmente i diritti per la finale al MetLife Stadium con una capacità di oltre 82.500 persone il 19 luglio 2026.",
        "wc26_preparation": "PREPARAZIONE",
        "wc26_prep_title": "Gli Stati Uniti accelerano i trasporti e l\'infrastruttura di sicurezza per un numero record di tifosi",
        "wc26_prep_desc": "Il governo federale ha approvato un budget speciale per aggiornare metropolitane e aviazione per collegare direttamente le città sede...",
        "wc26_view_now": "GUARDA ORA ➔",
        "wc26_general_news": "📰 NOTIZIE GENERALI",
        "wc26_general_news_desc": "Vedi eventi sportivi, trasferimenti e notizie delle leghe nelle ultime 24 ore",
        "league_center_title": "CENTRO LEGHE",
        "league_center_subtitle": "Classifiche e statistiche globali",
        "tab_scorers": "MARCATORI",
        "tab_assists": "ASSIST",
        "share_title": "CONDIVIDI PARTITA",
        "share_score_title": "Risultato e Stato",
        "share_score_desc": "Condividi i gol in tempo reale e lo stato della partita.",
        "share_stats_title": "Statistiche Dettagliate",
        "share_stats_desc": "Condividi possesso palla, tiri e calci d\'angolo.",
        "share_full_title": "Rapporto Completo della Partita",
        "share_full_desc": "Condividi il rapport completo combinando punteggio e statistiche.",
        "share_via": "Condividi tramite",
        "share_copied_toast": "Copiato negli appunti!",
        "reminder_set_toast": "Promemoria attivato per la partita!",
        "reminder_cancelled_toast": "Promemoria disattivato per la partita!",
        "share_caption_template": "Scopri le statistiche della partita %1$s vs %2$s su livescore://match/%3$d (Scarica l\\'app: https://livescore.premium/download)"
    },
    
    # Indonesian (id)
    "id": {
        "app_name": "LiveScore Premium",
        "nav_live": "Langsung",
        "nav_news": "Berita",
        "nav_favorite": "Favorit",
        "nav_profile": "Profil",
        "wc26": "Piala Dunia 26",
        "favorite_title": "FAVORIT",
        "my_follow": "IKUTI",
        "my_matches": "PERTANDINGAN",
        "live": "LANGSUNG",
        "upcoming": "MENDATANG",
        "finished": "SELESAI",
        "empty_matches": "Belum ada pertandingan favorit",
        "empty_leagues": "Belum ada liga favorit",
        "empty_teams": "Belum ada tim favorit",
        "empty_players": "Belum ada pemain favorit",
        "profile_title": "PROFIL SAYA",
        "language": "Bahasa",
        "premium_badge": "👑 ANGGOTA PREMIUM",
        "free_plan": "PAKET GRATIS",
        "daily_limit": "Batas Penggunaan API Harian",
        "upgrade_button": "UPGRADE SEKARANG",
        "intro_next": "Berikutnya",
        "intro_start": "Mulai",
        "intro_step_1_progress": "Langkah 1: 1/3",
        "intro_step_2_progress": "Langkah 2: 2/3",
        "intro_step_3_progress": "Langkah 3: 3/3",
        "intro_step_1_title": "PILIH LIGA FAVORIT",
        "intro_step_1_subtitle": "Filter berita & hasil pertandingan liga yang Anda minati",
        "intro_step_1_hint": "Cari liga...",
        "intro_step_2_title": "PILIH TIM YANG DIIKUTI",
        "intro_step_2_subtitle": "Kami akan memprioritaskan klub yang Anda pilih terlebih dahulu",
        "intro_step_2_hint": "Cari tim, klub...",
        "intro_step_3_title": "PILIH PEMAIN FAVORIT",
        "intro_step_3_subtitle": "Ikuti superstar sepak bola top dunia",
        "intro_step_3_hint": "Cari pemain...",
        "intro_finish": "SELESAI",
        "item_hot": " • Populer 🔥",
        "item_belongs": "Bagian dari: %1$s",
        "item_nationality": "Kewarganegaraan: %1$s",
        "intro_skip": "LEWATI",
        "intro_no_results": "Tidak ada hasil",
        "welcome_title": "SELAMAT DATANG DI LIVESCORE",
        "choose_language": "PILIH BAHASA",
        "choose_language_desc": "Pilih bahasa tampilan resmi aplikasi untuk melanjutkan pengaturan.",
        "profile_settings": "PENGATURAN",
        "profile_display_preferences": "TAMPILAN & PERSONALISASI",
        "profile_system": "PENYIMPANAN & SISTEM",
        "profile_about": "INFORMASI PERANGKAT LUNAK",
        "profile_version": "Versi",
        "language_dialog_title": "Pilih Bahasa",
        "language_changed_toast": "Bahasa diperbarui ke %1$s",
        "splash_app_title": "LIVESCORE",
        "splash_subtitle": "PUSAT OLAHRAGA PREMIUM",
        "tab_matches": "PERTANDINGAN",
        "tab_leagues": "LIGA",
        "empty_fixtures": "Pertandingan tidak ditemukan",
        "tab_standings": "KLASEMEN",
        "tab_fixtures": "PERTANDINGAN",
        "table_header_team": "TIM",
        "table_header_p": "Main",
        "table_header_w": "M",
        "table_header_d": "S",
        "table_header_l": "K",
        "table_header_gd": "SG",
        "table_header_pts": "POIN",
        "tab_stats": "STATISTIK",
        "tab_timeline": "LINIMASA",
        "tab_lineups": "FORMASI",
        "search_input_hint": "Cari pertandingan, tim, liga...",
        "search_empty_title": "Jelajahi Sepak Bola",
        "search_empty_desc": "Cari tim dan liga top seperti Liga Inggris, Real Madrid, Vietnam atau Piala Dunia 2026...",
        "news_center_title": "BERITA UTAMA 24 JAM",
        "news_featured_today": "⭐ SOROTAN HARI INI",
        "news_1_title": "FIFA secara resmi mengumumkan jadwal pertandingan Piala Dunia 2026 di AS, Meksiko, dan Kanada!",
        "news_1_desc": "Pertandingan pembukaan yang bersejarah akan berlangsung di Stadion Azteca yang terkenal di Meksiko. New York/New Jersey terpilih menyelenggarakan final.",
        "news_1_author": "Oleh Redaksi • Waktu baca 5 mnt",
        "news_detail_link": "Detail ➔",
        "news_2_title": "Arsenal bantai Chelsea 5-0 di Emirates, melesat luar biasa di klasemen",
        "news_2_desc": "Dua gol Ben White dan Kai Havertz membantu The Gunners menenggelamkan rival sekota dan mengirim sinyal ke Man City...",
        "news_2_time": "1 jam yang lalu • Waktu baca 3 mnt",
        "news_3_title": "Kylian Mbappé setujui kesepakatan awal untuk bergabung dengan Real Madrid",
        "news_3_desc": "Semua persyaratan pribadi telah disepakati. Superstar Prancis itu akan berlabuh ke Bernabeu dengan status bebas transfer dan bonus pemecah rekor...",
        "news_3_time": "3 jam yang lalu • Waktu baca 4 mnt",
        "news_4_title": "Skenario gila di semifinal: Real Madrid lakukan comeback ajaib bungkam Bayern Munchen",
        "news_4_desc": "Dua gol cepat Joselu di masa injury time membakar Santiago Bernabéu, mengirim Real Madrid ke final...",
        "news_4_time": "Kemarin • Waktu baca 6 mnt",
        "wc26_days_until": "Tersisa %1$d hari menuju Upacara Pembukaan",
        "wc26_starts_today": "⚽ KICKOFF HARI INI!",
        "wc26_ongoing": "⚽ Piala Dunia 2026 sedang berlangsung!",
        "wc26_groups": "GRUP",
        "wc26_teams": "TIM",
        "wc26_news": "BERITA",
        "wc26_opening_match": "Pertandingan Pembuka • Pekan 1",
        "wc26_azteca_stadium": "Stadion Azteca, Mexico City",
        "wc26_metlife_stadium": "Stadion MetLife, New York",
        "wc26_vs": "vs",
        "wc26_round_1_group_a": "Pekan 1 • Grup A",
        "wc26_group_a": "GRUP A",
        "wc26_group_b": "GRUP B",
        "wc26_qualified_teams": "TIM YANG LOLOS",
        "wc26_exclusive_news": "BERITA EKSKLUSIF",
        "wc26_exclusive_news_title": "Final Piala Dunia 2026 akan diselenggarakan megah di New York/New Jersey!",
        "wc26_exclusive_news_desc": "FIFA secara resmi memberikan hak tuan rumah final kepada MetLife Stadium dengan kapasitas lebih dari 82,500 kursi pada 19 Juli 2026.",
        "wc26_preparation": "PERSIAPAN",
        "wc26_prep_title": "AS percepat infrastruktur transportasi dan keamanan menyambut rekor jumlah penonton",
        "wc26_prep_desc": "Pemerintah federal telah menyetujui anggaran khusus untuk meningkatkan jaringan kereta bawah tanah dan penerbangan...",
        "wc26_view_now": "LIHAT SEKARANG ➔",
        "wc26_general_news": "📰 BERITA UMUM",
        "wc26_general_news_desc": "Lihat semua ajang olahraga, bursa transfer & berita liga dalam 24 jam terakhir",
        "league_center_title": "PUSAT LIGA",
        "league_center_subtitle": "Klasemen & statistik global",
        "tab_scorers": "PENCETAK GOL",
        "tab_assists": "ASSIST",
        "share_title": "BAGIKAN PERTANDINGAN",
        "share_score_title": "Skor &amp; Status",
        "share_score_desc": "Bagikan gol waktu nyata dan status pertandingan.",
        "share_stats_title": "Statistik Detail",
        "share_stats_desc": "Bagikan penguasaan bola, tembakan, dan sepak pojok.",
        "share_full_title": "Laporan Pertandingan Lengkap",
        "share_full_desc": "Bagikan laporan lengkap yang menggabungkan skor dan statistik.",
        "share_via": "Bagikan melalui",
        "share_copied_toast": "Tersalin ke papan klip!",
        "reminder_set_toast": "Pengingat pertandingan diaktifkan!",
        "reminder_cancelled_toast": "Pengingat pertandingan dinonaktifkan!",
        "share_caption_template": "Lihat statistik pertandingan %1$s vs %2$s di livescore://match/%3$d (Unduh aplikasi: https://livescore.premium/download)"
    },
    
    # Hindi (hi)
    "hi": {
        "app_name": "लाइवस्कोर प्रीमियम",
        "nav_live": "लाइव",
        "nav_news": "समाचार",
        "nav_favorite": "पसंदीदा",
        "nav_profile": "प्रोफ़ाइल",
        "wc26": "विश्व कप 26",
        "favorite_title": "पसंदीदा",
        "my_follow": "आपके फ़ॉलो",
        "my_matches": "आपके मैच",
        "live": "लाइव",
        "upcoming": "आगामी",
        "finished": "समाप्त",
        "empty_matches": "अभी कोई पसंदीदा मैच नहीं है",
        "empty_leagues": "अभी कोई पसंदीदा लीग नहीं है",
        "empty_teams": "अभी कोई पसंदीदा टीम नहीं है",
        "empty_players": "अभी कोई पसंदीदा खिलाड़ी नहीं है",
        "profile_title": "मेरी प्रोफ़ाइल",
        "language": "भाषा",
        "premium_badge": "👑 प्रीमियम सदस्य",
        "free_plan": "निःशुल्क योजना",
        "daily_limit": "दैनिक एपीआई उपयोग सीमा",
        "upgrade_button": "अभी अपग्रेड करें",
        "intro_next": "आगे",
        "intro_start": "शुरू करें",
        "intro_step_1_progress": "चरण 1: 1/3",
        "intro_step_2_progress": "चरण 2: 2/3",
        "intro_step_3_progress": "चरण 3: 3/3",
        "intro_step_1_title": "पसंदीदा लीग चुनें",
        "intro_step_1_subtitle": "अपनी पसंदीदा लीग के समाचार और परिणाम फ़िल्टर करें",
        "intro_step_1_hint": "लीग खोजें...",
        "intro_step_2_title": "अपने फ़ॉलो किए जाने वाले क्लब चुनें",
        "intro_step_2_subtitle": "हम आपके द्वारा चुने गए क्लबों को प्राथमिकता देंगे",
        "intro_step_2_hint": "टीम, क्लब खोजें...",
        "intro_step_3_title": "पसंदीदा खिलाड़ी चुनें",
        "intro_step_3_subtitle": "दुनिया के शीर्ष फुटबॉल सुपरस्टार को फ़ॉलो करें",
        "intro_step_3_hint": "खिलाड़ी खोजें...",
        "intro_finish": "समाप्त",
        "item_hot": " • लोकप्रिय 🔥",
        "item_belongs": "संबंधित है: %1$s",
        "item_nationality": "राष्ट्रीयता: %1$s",
        "intro_skip": "छोड़ें",
        "intro_no_results": "कोई परिणाम नहीं मिला",
        "welcome_title": "लाइवस्कोर में आपका स्वागत है",
        "choose_language": "भाषा चुनें",
        "choose_language_desc": "आगे बढ़ने के लिए ऐप की आधिकारिक प्रदर्शन भाषा चुनें।",
        "profile_settings": "सेटिंग्स",
        "profile_display_preferences": "प्रदर्शन और वैयक्तिकरण",
        "profile_system": "भंडारण और प्रणाली",
        "profile_about": "सॉफ्टवेयर जानकारी",
        "profile_version": "संस्करण",
        "language_dialog_title": "भाषा चुनें",
        "language_changed_toast": "भाषा %1$s पर अपडेट की गई",
        "splash_app_title": "लाइवस्कोर",
        "splash_subtitle": "प्रीमियम स्पोर्ट्स हब",
        "tab_matches": "मैच",
        "tab_leagues": "लीग",
        "empty_fixtures": "कोई मैच नहीं मिला",
        "tab_standings": "अंक तालिका",
        "tab_fixtures": "मैच",
        "table_header_team": "टीम",
        "table_header_p": "खेले",
        "table_header_w": "जीत",
        "table_header_d": "ड्रॉ",
        "table_header_l": "हार",
        "table_header_gd": "गोल अंतर",
        "table_header_pts": "अंक",
        "tab_stats": "आंकड़े",
        "tab_timeline": "समयरेखा",
        "tab_lineups": "लाइनअप",
        "search_input_hint": "मैच, टीम, लीग खोजें...",
        "search_empty_title": "फुटबॉल खोजें",
        "search_empty_desc": "प्रीमियर लीग, रियल मैड्रिड, वियतनाम या विश्व कप 2026 जैसी शीर्ष टीमों और लीगों को खोजें...",
        "news_center_title": "24 घंटे समाचार",
        "news_featured_today": "⭐ आज के मुख्य समाचार",
        "news_1_title": "फीफा ने आधिकारिक तौर पर अमेरिका, मैक्सिको और कनाडा में होने वाले 2026 विश्व कप के कार्यक्रम की घोषणा की!",
        "news_1_desc": "ऐतिहासिक उद्घाटन मैच मैक्सिको के प्रसिद्ध एज़्टेका स्टेडियम में खेला जाएगा। न्यूयॉर्क/न्यू जर्सी को फाइनल की मेजबानी मिली है।",
        "news_1_author": "संपादकीय बोर्ड द्वारा • 5 मिनट का पाठ",
        "news_detail_link": "विवरण ➔",
        "news_2_title": "आर्सेनल ने एमिरेट्स में चेल्सी को 5-0 से हराया, तालिका में शानदार छलांग लगाई",
        "news_2_desc": "बेन व्हाइट और काई हैवर्ट के दोहरे गोल ने गनर्स को अपने शहर के प्रतिद्वंद्वियों को हराने में मदद की और मैन सिटी को संदेश भेजा...",
        "news_2_time": "1 घंटे पहले • 3 मिनट का पाठ",
        "news_3_title": "कायलियन एम्बाप्पे ने रियल मैड्रिड में शामिल होने के लिए प्राथमिक शर्तों पर सहमति व्यक्त की",
        "news_3_desc": "सभी व्यक्तिगत शर्तों पर सहमति बन गई है। फ्रांसीसी सुपरस्टार रिकॉर्ड साइनिंग बोनस के साथ फ्री एजेंट के रूप में बर्नब्यू पहुंचेंगे...",
        "news_3_time": "3 घंटे पहले • 4 मिनट का पाठ",
        "news_4_title": "सेमीफाइनल में पागलपन: रियल मैड्रिड ने बायर्न म्यूनिख के खिलाफ चमत्कारिक वापसी की",
        "news_4_desc": "इंजुरी टाइम में जोसफ के दो त्वरित गोलों ने बर्नब्यू को जीत दिलाई, रियल मैड्रिड को फाइनल में भेजा...",
        "news_4_time": "कल • 6 मिनट का पाठ",
        "wc26_days_until": "उद्घाटन समारोह के लिए %1$d दिन शेष",
        "wc26_starts_today": "⚽ आज से शुरुआत!",
        "wc26_ongoing": "⚽ विश्व कप 2026 जारी है!",
        "wc26_groups": "ग्रुप",
        "wc26_teams": "टीमें",
        "wc26_news": "समाचार",
        "wc26_opening_match": "उद्घाटन मैच • दौर 1",
        "wc26_azteca_stadium": "एज़्टेका स्टेडियम, मैक्सिको सिटी",
        "wc26_metlife_stadium": "मेटलाइफ़ स्टेडियम, न्यूयॉर्क",
        "wc26_vs": "बनाम",
        "wc26_round_1_group_a": "दौर 1 • ग्रुप ए",
        "wc26_group_a": "ग्रुप ए",
        "wc26_group_b": "ग्रुप बी",
        "wc26_qualified_teams": "योग्य टीमें",
        "wc26_exclusive_news": "विशेष समाचार",
        "wc26_exclusive_news_title": "2026 विश्व कप का फाइनल न्यूयॉर्क/न्यू जर्सी में भव्य रूप से आयोजित किया जाएगा!",
        "wc26_exclusive_news_desc": "फीफा ने आधिकारिक तौर पर 19 जुलाई 2026 को 82,500 से अधिक क्षमता वाले मेटलाइफ स्टेडियम को फाइनल की मेजबानी का अधिकार दिया।",
        "wc26_preparation": "तैयारी",
        "wc26_prep_title": "अमेरिका ने रिकॉर्ड प्रशंसकों के लिए परिवहन और सुरक्षा बुनियादी ढांचे को तेज किया",
        "wc26_prep_desc": "संघीय सरकार ने मेजबान शहरों को सीधे जोड़ने वाले सबवे और विमानन को अपग्रेड करने के लिए विशेष बजट को मंजूरी दी...",
        "wc26_view_now": "अभी देखें ➔",
        "wc26_general_news": "📰 सामान्य समाचार",
        "wc26_general_news_desc": "पिछले 24 घंटों के सभी खेल आयोजन, स्थानांतरण और लीग समाचार देखें",
        "league_center_title": "लीग केंद्र",
        "league_center_subtitle": "वैश्विक स्थिति और आंकड़े",
        "tab_scorers": "शीर्ष स्कोरर",
        "tab_assists": "सहायता",
        "share_title": "मैच साझा करें",
        "share_score_title": "स्कोर और स्थिति",
        "share_score_desc": "वास्तविक समय के गोल और मैच की स्थिति साझा करें।",
        "share_stats_title": "विस्तृत मैच आंकड़े",
        "share_stats_desc": "कब्जा, शॉट और कॉर्नर किक साझा करें।",
        "share_full_title": "पूर्ण मैच रिपोर्ट",
        "share_full_desc": "स्कोर और आंकड़ों को मिलाकर पूर्ण रिपोर्ट साझा करें।",
        "share_via": "के माध्यम से साझा करें",
        "share_copied_toast": "क्लिपबोर्ड पर कॉपी किया गया!",
        "reminder_set_toast": "मैच के लिए अनुस्मारक सक्रिय!",
        "reminder_cancelled_toast": "मैच के लिए अनुस्मारक निष्क्रिय!",
        "share_caption_template": "livescore://match/%3$d पर %1$s बनाम %2$s के मैच आंकड़े देखें (ऐप डाउनलोड करें: https://livescore.premium/download)"
    },
    
    # Turkish (tr)
    "tr": {
        "app_name": "LiveScore Premium",
        "nav_live": "Canlı",
        "nav_news": "Haberler",
        "nav_favorite": "Favoriler",
        "nav_profile": "Profil",
        "wc26": "Dünya Kupası 26",
        "favorite_title": "FAVORİLER",
        "my_follow": "TAKİPLERİNİZ",
        "my_matches": "MAÇLARINIZ",
        "live": "CANLI",
        "upcoming": "GELECEK",
        "finished": "BİTMİŞ",
        "empty_matches": "Henüz favori maç yok",
        "empty_leagues": "Henüz favori lig yok",
        "empty_teams": "Henüz favori takım yok",
        "empty_players": "Henüz favori oyuncu yok",
        "profile_title": "PROFİLİM",
        "language": "Dil",
        "premium_badge": "👑 PREMIUM ÜYE",
        "free_plan": "ÜCRETSİZ PLAN",
        "daily_limit": "Günlük API Kullanım Sınırı",
        "upgrade_button": "ŞİMDİ YÜKSELT",
        "intro_next": "İleri",
        "intro_start": "Başla",
        "intro_step_1_progress": "Adım 1: 1/3",
        "intro_step_2_progress": "Adım 2: 2/3",
        "intro_step_3_progress": "Adım 3: 3/3",
        "intro_step_1_title": "FAVORİ LİGLERİ SEÇİN",
        "intro_step_1_subtitle": "İlgilendiğiniz liglerin haberlerini & sonuçlarını filtreleyin",
        "intro_step_1_hint": "Lig ara...",
        "intro_step_2_title": "TAKİP ETTİĞİNİZ TAKIMLARI SEÇİN",
        "intro_step_2_subtitle": "Öncelikli olarak seçtiğiniz kulüpleri göstereceğiz",
        "intro_step_2_hint": "Takım, kulüp ara...",
        "intro_step_3_title": "FAVORİ OYUNCULARI SEÇİN",
        "intro_step_3_subtitle": "Dünyanın en iyi futbol süper starlarını takip edin",
        "intro_step_3_hint": "Oyuncu ara...",
        "intro_finish": "BİTİR",
        "item_hot": " • Popüler 🔥",
        "item_belongs": "Ait olduğu yer: %1$s",
        "item_nationality": "Uyruk: %1$s",
        "intro_skip": "ATLA",
        "intro_no_results": "Sonuç bulunamadı",
        "welcome_title": "LIVESCORE\'A HOŞ GELDİNİZ",
        "choose_language": "DİL SEÇİN",
        "choose_language_desc": "Kişiselleştirilmiş kuruluma devam etmek için uygulamanın resmi dilini seçin.",
        "profile_settings": "AYARLAR",
        "profile_display_preferences": "GÖRÜNÜM & KİŞİSELLEŞTİRME",
        "profile_system": "DEPOLAMA & SİSTEM",
        "profile_about": "YAZILIM BİLGİSİ",
        "profile_version": "Sürüm",
        "language_dialog_title": "Dil Seçin",
        "language_changed_toast": "Dil %1$s olarak güncellendi",
        "splash_app_title": "LIVESCORE",
        "splash_subtitle": "PREMIUM SPOR MERKEZİ",
        "tab_matches": "MAÇLAR",
        "tab_leagues": "LİGLER",
        "empty_fixtures": "Maç bulunamadı",
        "tab_standings": "PUAN DURUMU",
        "tab_fixtures": "MAÇLAR",
        "table_header_team": "TAKIM",
        "table_header_p": "O",
        "table_header_w": "G",
        "table_header_d": "B",
        "table_header_l": "M",
        "table_header_gd": "AV",
        "table_header_pts": "PTS",
        "tab_stats": "İSTATİSTİK",
        "tab_timeline": "ZAMAN TÜNELİ",
        "tab_lineups": "KADROLAR",
        "search_input_hint": "Maç, takım, lig ara...",
        "search_empty_title": "Futbolu Keşfet",
        "search_empty_desc": "Premier Lig, Real Madrid, Vietnam veya Dünya Kupası 2026 gibi en iyi takımları ve ligleri arayın...",
        "news_center_title": "24 SAAT SICAK HABERLER",
        "news_featured_today": "⭐ BUGÜNÜN ÖNE ÇIKANLARI",
        "news_1_title": "FIFA, ABD, Meksika ve Kanada\'daki 2026 Dünya Kupası maç programını resmen açıkladı!",
        "news_1_desc": "Tarihi açılış maçı Meksika\'nın ünlü Azteca Stadyumu\'nda oynanacak. New York/New Jersey finali düzenleme hakkını kazandı.",
        "news_1_author": "Editör Kurulu Tarafından • 5 dk okuma",
        "news_detail_link": "Detaylar ➔",
        "news_2_title": "Arsenal, Emirates\'te Chelsea\'yi 5-0 ezdi, puan durumunda müthiş bir sıçrama yaptı",
        "news_2_desc": "Ben White ve Kai Havertz\'in çift golleri Gunners\'ın şehir rakiplerini batırmasına ve Man City\'e bir mesaj göndermesine yardımcı oldu...",
        "news_2_time": "1 saat önce • 3 dk okuma",
        "news_3_title": "Kylian Mbappé, Real Madrid\'e katılmak için ön şartları kabul etti",
        "news_3_desc": "Tüm kişisel şartlar üzerinde anlaşıldı. Fransız süper star, rekor imza bonusu ile serbest oyuncu olarak Bernabeu\'ya inecek...",
        "news_3_time": "3 saat önce • 4 dk okuma",
        "news_4_title": "Yarı finalde çılgın senaryo: Real Madrid, Bayern Münih\'e karşı mucizevi bir geri dönüş yaptı",
        "news_4_desc": "Uzatma dakikalarında Joselu\'nun hızlı iki golü Bernabéu\'yu ayağa kaldırdı ve Real Madrid\'i finale gönderdi...",
        "news_4_time": "Dün • 6 dk okuma",
        "wc26_days_until": "Açılış Törenine %1$d gün kaldı",
        "wc26_starts_today": "⚽ BUGÜN BAŞLIYOR!",
        "wc26_ongoing": "⚽ Dünya Kupası 2026 devam ediyor!",
        "wc26_groups": "GRUPLAR",
        "wc26_teams": "TAKIMLAR",
        "wc26_news": "HABERLER",
        "wc26_opening_match": "Açılış Maçı • 1. Hafta",
        "wc26_azteca_stadium": "Azteca Stadyumu, Mexico City",
        "wc26_metlife_stadium": "MetLife Stadyumu, New York",
        "wc26_vs": "vs",
        "wc26_round_1_group_a": "1. Hafta • A Grubu",
        "wc26_group_a": "A GRUBU",
        "wc26_group_b": "B GRUBU",
        "wc26_qualified_teams": "KATILAN TAKIMLAR",
        "wc26_exclusive_news": "ÖZEL HABER",
        "wc26_exclusive_news_title": "Dünya Kupası 2026 finali görkemli bir şekilde New York/New Jersey\'de yapılacak!",
        "wc26_exclusive_news_desc": "FIFA, finalin ev sahipliği haklarını resmen 19 Temmuz 2026\'da 82.500\'den fazla kapasiteli MetLife Stadyumu\'na verdi.",
        "wc26_preparation": "HAZIRLIKLAR",
        "wc26_prep_title": "ABD, rekor taraftar sayısı için ulaşım ve güvenlik altyapısını hızlandırıyor",
        "wc26_prep_desc": "Federal hükümet, ev sahibi şehirleri doğrudan birbirine bağlayan metro ve havacılığı yükseltmek için özel bir bütçe paketini onayladı...",
        "wc26_view_now": "ŞİMDİ İZLE ➔",
        "wc26_general_news": "📰 GENEL HABERLER",
        "wc26_general_news_desc": "Son 24 saatteki tüm spor etkinliklerini, transferleri & lig haberlerini görün",
        "league_center_title": "LİG MERKEZİ",
        "league_center_subtitle": "Küresel puan durumları & istatistikler",
        "tab_scorers": "GOL KRALLIĞI",
        "tab_assists": "ASİSTLER",
        "share_title": "MAÇI PAYLAŞ",
        "share_score_title": "Skor ve Durum",
        "share_score_desc": "Gerçek zamanlı golleri ve maç durumunu paylaşın.",
        "share_stats_title": "Detaylı Maç İstatistikleri",
        "share_stats_desc": "Topa sahip olma, şut ve köşe vuruşlarını paylaşın.",
        "share_full_title": "Tam Maç Raporu",
        "share_full_desc": "Skorları ve istatistikleri birleştiren tam raporu paylaşın.",
        "share_via": "Şununla paylaş",
        "share_copied_toast": "Panoya kopyalandı!",
        "reminder_set_toast": "Maç hatırlatıcısı etkinleştirildi!",
        "reminder_cancelled_toast": "Maç hatırlatıcısı devre dışı bırakıldı!",
        "share_caption_template": "%1$s - %2$s maç istatistiklerini livescore://match/%3$d adresinde inceleyin (Uygulamayı indirin: https://livescore.premium/download)"
    },
    
    # Japanese (ja)
    "ja": {
        "app_name": "LiveScore プレミアム",
        "nav_live": "ライブ",
        "nav_news": "ニュース",
        "nav_favorite": "お気に入り",
        "nav_profile": "プロファイル",
        "wc26": "W杯 26",
        "favorite_title": "お気に入り",
        "my_follow": "フォロー中",
        "my_matches": "登録試合",
        "live": "ライブ",
        "upcoming": "今後の予定",
        "finished": "終了",
        "empty_matches": "お気に入りの試合はまだありません",
        "empty_leagues": "お気に入りのリーグはまだありません",
        "empty_teams": "お気に入りのチームはまだありません",
        "empty_players": "お気に入り選手はまだありません",
        "profile_title": "マイ プロファイル",
        "language": "言語",
        "premium_badge": "👑 プレミアム会員",
        "free_plan": "無料プラン",
        "daily_limit": "1日あたりのAPI使用制限",
        "upgrade_button": "今すぐアップグレード",
        "intro_next": "次へ",
        "intro_start": "スタート",
        "intro_step_1_progress": "ステップ 1: 1/3",
        "intro_step_2_progress": "ステップ 2: 2/3",
        "intro_step_3_progress": "ステップ 3: 3/3",
        "intro_step_1_title": "お気に入りリーグを選択",
        "intro_step_1_subtitle": "関心のあるリーグのニュースと結果をフィルターします",
        "intro_step_1_hint": "リーグを検索...",
        "intro_step_2_title": "フォローするチームを選択",
        "intro_step_2_subtitle": "選択したクラブを優先的に表示します",
        "intro_step_2_hint": "チーム、クラブを検索...",
        "intro_step_3_title": "お気に入り選手を選択",
        "intro_step_3_subtitle": "世界のトップサッカー選手をフォローします",
        "intro_step_3_hint": "選手を検索...",
        "intro_finish": "完了",
        "item_hot": " • 人気 🔥",
        "item_belongs": "所属: %1$s",
        "item_nationality": "国籍: %1$s",
        "intro_skip": "スキップ",
        "intro_no_results": "結果が見つかりません",
        "welcome_title": "ライブスコアへようこそ",
        "choose_language": "言語の選択",
        "choose_language_desc": "パーソナライズされた設定を進めるために、アプリの公式表示言語を選択してください。",
        "profile_settings": "設定",
        "profile_display_preferences": "表示とカスタマイズ",
        "profile_system": "ストレージとシステム",
        "profile_about": "ソフトウェア情報",
        "profile_version": "バージョン",
        "language_dialog_title": "言語を選択",
        "language_changed_toast": "言語が %1$s に更新されました",
        "splash_app_title": "ライブスコア",
        "splash_subtitle": "プレミアム スポーツ ハブ",
        "tab_matches": "試合",
        "tab_leagues": "リーグ",
        "empty_fixtures": "試合が見つかりません",
        "tab_standings": "順位表",
        "tab_fixtures": "試合",
        "table_header_team": "チーム",
        "table_header_p": "試",
        "table_header_w": "勝",
        "table_header_d": "分",
        "table_header_l": "敗",
        "table_header_gd": "得失",
        "table_header_pts": "点",
        "tab_stats": "スタッツ",
        "tab_timeline": "タイムライン",
        "tab_lineups": "スタメン",
        "search_input_hint": "試合、チーム、リーグを検索...",
        "search_empty_title": "サッカーを探索",
        "search_empty_desc": "プレミアリーグ、レアル・マドリード、日本、またはW杯2026などのトップチームやリーグを検索...",
        "news_center_title": "24時間ホットニュース",
        "news_featured_today": "⭐ 今日の特集",
        "news_1_title": "FIFAがアメリカ、メキシコ、カナダで開催される2026年W杯の試合日程を正式に発表！",
        "news_1_desc": "歴史的な開幕戦はメキシコの有名なアステカ・スタジアムで行われます。ニューヨーク／ニュージャージーが決勝戦の開催権を獲得しました。",
        "news_1_author": "編集部より • 読了まで5分",
        "news_detail_link": "詳細 ➔",
        "news_2_title": "アーセナルがエミレーツでチェルシーを5-0で圧倒し、順位表で劇的な躍進を遂げる",
        "news_2_desc": "ベン・ホワイトとカイ・ハフェルツの2ゴールがガナーズを勝利に導き、マン・シティに強力なメッセージを送りました...",
        "news_2_time": "1時間前 • 読了まで3分",
        "news_3_title": "キリアン・エムバペがレアル・マドリード加入の基本条件に合意",
        "news_3_desc": "すべての個人条件が合意されました。フランスのスーパースターは、記録的な契約ボーナスとともにフリーエージェントとしてベルナベウに移籍します...",
        "news_3_time": "3時間前 • 読了まで4分",
        "news_4_title": "準決勝でのクレイジーなシナリオ：レアル・マドリードがバイエルン・ミュンヘンを相手に奇跡的な逆転劇を果たす",
        "news_4_desc": "アディショナルタイムでのホセルの素早い2ゴールがサンティアゴ・ベルナベウを沸かせ、レアル・マドリードを決勝へ導きました...",
        "news_4_time": "昨日 • 読了まで6分",
        "wc26_days_until": "開幕まであと %1$d 日",
        "wc26_starts_today": "⚽ 本日開幕！",
        "wc26_ongoing": "⚽ W杯 2026 開催中！",
        "wc26_groups": "グループ",
        "wc26_teams": "チーム",
        "wc26_news": "ニュース",
        "wc26_opening_match": "開幕戦 • ラウンド 1",
        "wc26_azteca_stadium": "アステカ・スタジアム（メキシコ・シティ）",
        "wc26_metlife_stadium": "メットライフ・スタジアム（ニューヨーク）",
        "wc26_vs": "vs",
        "wc26_round_1_group_a": "ラウンド 1 • グループ A",
        "wc26_group_a": "グループ A",
        "wc26_group_b": "グループ B",
        "wc26_qualified_teams": "出場国一覧",
        "wc26_exclusive_news": "独占ニュース",
        "wc26_exclusive_news_title": "W杯2026決勝はニューヨーク／ニュージャージーで盛大に開催決定！",
        "wc26_exclusive_news_desc": "FIFAは2026年7月19日、82,500人以上の収容人数を誇るメットライフ・スタジアムに決勝戦の開催権を正式に授与しました。",
        "wc26_preparation": "準備状況",
        "wc26_prep_title": "米国が史上最多のファンを迎え入れるために交通と安全のインフラ整備を加速",
        "wc26_prep_desc": "連邦政府は、開催都市を直接結ぶ地下鉄や航空のアップグレードに関する特別予算を承認しました...",
        "wc26_view_now": "今すぐ見る ➔",
        "wc26_general_news": "📰 総合ニュース",
        "wc26_general_news_desc": "過去24時間の全スポーツイベント、移籍情報、リーグのニュースを表示",
        "league_center_title": "リーグセンター",
        "league_center_subtitle": "グローバル順位表＆スタッツ",
        "tab_scorers": "得点王",
        "tab_assists": "アシスト",
        "share_title": "試合をシェア",
        "share_score_title": "スコアと状態",
        "share_score_desc": "リアルタイムのゴールと試合状況を共有します。",
        "share_stats_title": "詳細な試合スタッツ",
        "share_stats_desc": "支配率、シュート、コーナーキックを共有します。",
        "share_full_title": "完全な試合レポート",
        "share_full_desc": "スコアとスタッツを組み合わせた完全なレポートを共有します。",
        "share_via": "共有方法",
        "share_copied_toast": "クリップボードにコピーされました！",
        "reminder_set_toast": "試合のリマインダーが有効になりました！",
        "reminder_cancelled_toast": "試合のリマインダーが解除されました！",
        "share_caption_template": "livescore://match/%3$d で %1$s vs %2$s の試合統計をチェック！ (アプリをダウンロード: https://livescore.premium/download)"
    },
    
    # Thai (th)
    "th": {
        "app_name": "LiveScore Premium",
        "nav_live": "สด",
        "nav_news": "ข่าว",
        "nav_favorite": "รายการโปรด",
        "nav_profile": "โปรไฟล์",
        "wc26": "ฟุตบอลโลก 26",
        "favorite_title": "รายการโปรด",
        "my_follow": "ที่คุณติดตาม",
        "my_matches": "การแข่งขันของคุณ",
        "live": "สด",
        "upcoming": "เร็วๆ นี้",
        "finished": "สิ้นสุดแล้ว",
        "empty_matches": "ยังไม่มีคู่โปรดของคุณ",
        "empty_leagues": "ยังไม่มีลีกโปรดของคุณ",
        "empty_teams": "ยังไม่มีทีมโปรดของคุณ",
        "empty_players": "ยังไม่มีผู้เล่นโปรดของคุณ",
        "profile_title": "โปรไฟล์ของฉัน",
        "language": "ภาษา",
        "premium_badge": "👑 สมาชิกพรีเมียม",
        "free_plan": "แพ็กเกจฟรี",
        "daily_limit": "ลิมิตการใช้งาน API รายวัน",
        "upgrade_button": "อัปเกรดตอนนี้",
        "intro_next": "ถัดไป",
        "intro_start": "เริ่มต้น",
        "intro_step_1_progress": "ขั้นตอน 1: 1/3",
        "intro_step_2_progress": "ขั้นตอน 2: 2/3",
        "intro_step_3_progress": "ขั้นตอน 3: 3/3",
        "intro_step_1_title": "เลือกลีกที่คุณชื่นชอบ",
        "intro_step_1_subtitle": "กรองข่าวและผลการแข่งขันลีกที่คุณสนใจ",
        "intro_step_1_hint": "ค้นหาลีก...",
        "intro_step_2_title": "เลือกทีมที่คุณติดตาม",
        "intro_step_2_subtitle": "เราจะจัดลำดับความสำคัญของสโมสรที่คุณเลือกไว้เป็นลำดับแรก",
        "intro_step_2_hint": "ค้นหาทีม, สโมสร...",
        "intro_step_3_title": "เลือกผู้เล่นที่คุณชอบ",
        "intro_step_3_subtitle": "ติดตามซูเปอร์สตาร์ฟุตบอลชั้นนำของโลก",
        "intro_step_3_hint": "ค้นหาผู้เล่น...",
        "intro_finish": "เสร็จสิ้น",
        "item_hot": " • ยอดนิยม 🔥",
        "item_belongs": "สังกัด: %1$s",
        "item_nationality": "สัญชาติ: %1$s",
        "intro_skip": "ข้าม",
        "intro_no_results": "ไม่พบผลลัพธ์",
        "welcome_title": "ยินดีต้อนรับสู่ LiveScore",
        "choose_language": "เลือกภาษา",
        "choose_language_desc": "เลือกภาษาหลักในการแสดงผลของแอปเพื่อทำการตั้งค่าต่อ",
        "profile_settings": "การตั้งค่า",
        "profile_display_preferences": "การแสดงผลและการตั้งค่าส่วนตัว",
        "profile_system": "การจัดเก็บและระบบ",
        "profile_about": "ข้อมูลซอฟต์แวร์",
        "profile_version": "เวอร์ชัน",
        "language_dialog_title": "เลือกภาษา",
        "language_changed_toast": "อัปเดตภาษาเป็น %1$s แล้ว",
        "splash_app_title": "LIVESCORE",
        "splash_subtitle": "ศูนย์รวมกีฬาพรีเมียม",
        "tab_matches": "การแข่งขัน",
        "tab_leagues": "ลีก",
        "empty_fixtures": "ไม่พบการแข่งขัน",
        "tab_standings": "ตารางคะแนน",
        "tab_fixtures": "การแข่งขัน",
        "table_header_team": "ทีม",
        "table_header_p": "แข่ง",
        "table_header_w": "ชนะ",
        "table_header_d": "เสมอ",
        "table_header_l": "แพ้",
        "table_header_gd": "ได้เสีย",
        "table_header_pts": "แต้ม",
        "tab_stats": "สถิติ",
        "tab_timeline": "ไทม์ไลน์",
        "tab_lineups": "ผู้เล่นตัวจริง",
        "search_input_hint": "ค้นหาแมตช์, ทีม, ลีก...",
        "search_empty_title": "สำรวจฟุตบอล",
        "search_empty_desc": "ค้นหาทีมและลีกชั้นนำ เช่น พรีเมียร์ลีก, เรอัล มาดริด, ทีมชาติไทย หรือฟุตบอลโลก 2026...",
        "news_center_title": "ข่าวร้อน 24 ชม.",
        "news_featured_today": "⭐ แนะนำวันนี้",
        "news_1_title": "ฟีฟ่าประกาศตารางการแข่งขันฟุตบอลโลก 2026 ในสหรัฐฯ เม็กซิโก และแคนาดา อย่างเป็นทางการ!",
        "news_1_desc": "นัดเปิดสนามครั้งประวัติศาสตร์จะจัดขึ้นที่สนามเอสตาดิโอ อัซเตกา อันเลื่องชื่อของเม็กซิโก นครนิวยอร์ก/นิวเจอร์ซีย์ ได้รับสิทธิ์จัดรอบชิงชนะเลิศ",
        "news_1_author": "โดยกองบรรณาธิการ • อ่าน 5 นาที",
        "news_detail_link": "รายละเอียด ➔",
        "news_2_title": "อาร์เซนอลถล่มเชลซี 5-0 ที่เอมิเรตส์สเตเดียม ทะยานสู่อันดับตารางอย่างยอดเยี่ยม",
        "news_2_desc": "ดับเบิ้ลประตูของเบน ไวท์ และไค ฮาแวร์ตซ์ ช่วยให้ทัพปืนใหญ่ถล่มคู่ปรับร่วมเมืองและส่งคำเตือนไปยังแมนฯ ซิตี้...",
        "news_2_time": "1 ชั่วโมงที่แล้ว • อ่าน 3 นาที",
        "news_3_title": "คีเลียน เอ็มบัปเป้ บรรลุข้อตกลงเบื้องต้นย้ายซบเรอัล มาดริด",
        "news_3_desc": "ข้อตกลงส่วนตัวเสร็จสิ้นแล้ว ซูเปอร์สตาร์ชาวฝรั่งเศสจะย้ายร่วมทัพราชันชุดขาวแบบไร้ค่าตัวพร้อมโบนัสการเซ็นสัญญาสถิติโลก...",
        "news_3_time": "3 ชั่วโมงที่แล้ว • อ่าน 4 นาที",
        "news_4_title": "ฉากสุดบ้าคลั่งในรอบรองชนะเลิศ: เรอัล มาดริด พลิกนรกชนะบาเยิร์น มิวนิก สุดดราม่า",
        "news_4_desc": "สองประตูช็อคโลกในช่วงทดเจ็บจากโฆเซลู ทำเอาสนามซานติอาโก เบร์นาเบว แทบแตก พร้อมพาราชันชุดขาวผ่านเข้ารอบชิงชนะเลิศ...",
        "news_4_time": "เมื่อวาน • อ่าน 6 นาที",
        "wc26_days_until": "เหลืออีก %1$d วันถึงพิธีเปิด",
        "wc26_starts_today": "⚽ เปิดสนามวันนี้!",
        "wc26_ongoing": "⚽ ฟุตบอลโลก 2026 กำลังแข่งขันอยู่!",
        "wc26_groups": "กลุ่ม",
        "wc26_teams": "ทีม",
        "wc26_news": "ข่าว",
        "wc26_opening_match": "แมตช์เปิดสนาม • รอบ 1",
        "wc26_azteca_stadium": "สนามอัซเตกา, เม็กซิโกซิตี้",
        "wc26_metlife_stadium": "สนามเมทไลฟ์, นิวยอร์ก",
        "wc26_vs": "vs",
        "wc26_round_1_group_a": "รอบ 1 • กลุ่มเอ",
        "wc26_group_a": "กลุ่มเอ",
        "wc26_group_b": "กลุ่มบี",
        "wc26_qualified_teams": "ทีมที่ผ่านเข้ารอบ",
        "wc26_exclusive_news": "ข่าวเอ็กซ์คลูซีฟ",
        "wc26_exclusive_news_title": "รอบชิงฟุตบอลโลก 2026 เตรียมจัดยิ่งใหญ่ที่นครนิวยอร์ก/นิวเจอร์ซีย์!",
        "wc26_exclusive_news_desc": "ฟีฟ่าได้มอบสิทธิ์การเป็นเจ้าภาพรอบชิงชนะเลิศอย่างเป็นทางการให้กับสนามเมทไลฟ์ สเตเดียม ความจุมากกว่า 82,500 ที่นั่ง ในวันที่ 19 กรกฎาคม 2026",
        "wc26_preparation": "การเตรียมการ",
        "wc26_prep_title": "สหรัฐฯ เร่งพัฒนาโครงสร้างการขนส่งและความมั่นคง เพื่อรองรับแฟนบอลจำนวนมหาศาล",
        "wc26_prep_desc": "รัฐบาลกลางอนุมัติแพ็กเกจงบประมาณพิเศษเพื่ออัปเกรดรถไฟใต้ดินและระบบการบินเชื่อมต่อตรงสู่เมืองเจ้าภาพ...",
        "wc26_view_now": "ดูตอนนี้ ➔",
        "wc26_general_news": "📰 ข่าวทั่วไป",
        "wc26_general_news_desc": "ดูข่าวการแข่งขันข่าวกีฬา ตลาดซื้อขาย และข่าวลีกรอบ 24 ชั่วโมงที่ผ่านมา",
        "league_center_title": "ศูนย์รวมลีก",
        "league_center_subtitle": "ตารางคะแนน & สถิติทั่วโลก",
        "tab_scorers": "ดาวซัลโว",
        "tab_assists": "แอสซิสต์",
        "share_title": "แชร์การแข่งขัน",
        "share_score_title": "ผลการแข่งขัน &amp; สถานะ",
        "share_score_desc": "แชร์ประตูแบบเรียลไทม์และสถานะการแข่งขัน",
        "share_stats_title": "สถิติอย่างละเอียด",
        "share_stats_desc": "แชร์อัตราการครองบอล, โอกาสยิง, และเตะมุม",
        "share_full_title": "รายงานการแข่งขันฉบับเต็ม",
        "share_full_desc": "แชร์รายงานฉบับเต็มที่รวมทั้งสกอร์และสถิติเข้าด้วยกัน",
        "share_via": "แชร์ผ่าน",
        "share_copied_toast": "คัดลอกไปยังคลิปบอร์ดแล้ว!",
        "reminder_set_toast": "เปิดการแจ้งเตือนสำหรับแมตช์นี้แล้ว!",
        "reminder_cancelled_toast": "ปิดการแจ้งเตือนสำหรับแมตช์นี้แล้ว!",
        "share_caption_template": "ดูสถิติการแข่งขันระหว่าง %1$s vs %2$s ที่ livescore://match/%3$d (ดาวน์โหลดแอป: https://livescore.premium/download)"
    },
    
    # Russian (ru)
    "ru": {
        "app_name": "LiveScore Premium",
        "nav_live": "Лайв",
        "nav_news": "Новости",
        "nav_favorite": "Избранное",
        "nav_profile": "Профиль",
        "wc26": "ЧМ-2026",
        "favorite_title": "ИЗБРАННОЕ",
        "my_follow": "МОИ ПОДПИСКИ",
        "my_matches": "МОИ МАТЧИ",
        "live": "ЛАЙВ",
        "upcoming": "СКОРО",
        "finished": "ЗАВЕРШЕННЫЕ",
        "empty_matches": "Нет любимых матчей",
        "empty_leagues": "Нет любимых лиг",
        "empty_teams": "Нет любимых команд",
        "empty_players": "Нет любимых игроков",
        "profile_title": "МОЙ ПРОФИЛЬ",
        "language": "Язык",
        "premium_badge": "👑 ПРЕМИУМ-ДОСТУП",
        "free_plan": "БЕСПЛАТНЫЙ ТАРИФ",
        "daily_limit": "Дневной лимит запросов API",
        "upgrade_button": "ОБНОВИТЬ СЕЙЧАС",
        "intro_next": "Далее",
        "intro_start": "Начать",
        "intro_step_1_progress": "Шаг 1: 1/3",
        "intro_step_2_progress": "Шаг 2: 2/3",
        "intro_step_3_progress": "Шаг 3: 3/3",
        "intro_step_1_title": "ВЫБЕРИТЕ ЛЮБИМЫЕ ЛИГИ",
        "intro_step_1_subtitle": "Фильтруйте новости и результаты интересующих вас лиг",
        "intro_step_1_hint": "Поиск лиг...",
        "intro_step_2_title": "ВЫБЕРИТЕ КОМАНДЫ, ЗА КОТОРЫМИ СЛЕДИТЕ",
        "intro_step_2_subtitle": "Мы будем показывать выбранные вами клубы первыми",
        "intro_step_2_hint": "Поиск команд, клубов...",
        "intro_step_3_title": "ВЫБЕРИТЕ ЛЮБИМЫХ ИГРОКОВ",
        "intro_step_3_subtitle": "Следите за лучшими суперзвездами мирового футбола",
        "intro_step_3_hint": "Поиск игроков...",
        "intro_finish": "ГОТОВО",
        "item_hot": " • Популярное 🔥",
        "item_belongs": "Клуб: %1$s",
        "item_nationality": "Гражданство: %1$s",
        "intro_skip": "ПРОПУСТИТЬ",
        "intro_no_results": "Результаты не найдены",
        "welcome_title": "ДОБРО ПОЖАЛОВАТЬ В LIVESCORE",
        "choose_language": "ВЫБЕРИТЕ ЯЗЫК",
        "choose_language_desc": "Выберите официальный язык приложения, чтобы продолжить персонализированную настройку.",
        "profile_settings": "НАСТРОЙКИ",
        "profile_display_preferences": "ОФОРМЛЕНИЕ И ПЕРСОНАЛИЗАЦИЯ",
        "profile_system": "ПАМЯТЬ И СИСТЕМА",
        "profile_about": "ИНФОРМАЦИЯ О ПО",
        "profile_version": "Версия",
        "language_dialog_title": "Выберите язык",
        "language_changed_toast": "Язык изменен на %1$s",
        "splash_app_title": "LIVESCORE",
        "splash_subtitle": "ПРЕМИАЛЬНЫЙ СПОРТИВНЫЙ ПОРТАЛ",
        "tab_matches": "МАТЧИ",
        "tab_leagues": "ЛИГИ",
        "empty_fixtures": "Матчи не найдены",
        "tab_standings": "ТАБЛИЦА",
        "tab_fixtures": "МАТЧИ",
        "table_header_team": "КОМАНДА",
        "table_header_p": "И",
        "table_header_w": "В",
        "table_header_d": "Н",
        "table_header_l": "П",
        "table_header_gd": "РМ",
        "table_header_pts": "О",
        "tab_stats": "СТАТИСТИКА",
        "tab_timeline": "ХРОНОЛОГИЯ",
        "tab_lineups": "СОСТАВЫ",
        "search_input_hint": "Поиск матчей, команд, лиг...",
        "search_empty_title": "Исследуйте футбол",
        "search_empty_desc": "Ищите топовые команды и лиги, такие как Английская Премьер-лига, Реал Мадрид, Россия или Чемпионат мира 2026...",
        "news_center_title": "ГОРЯЧИЕ НОВОСТИ 24Ч",
        "news_featured_today": "⭐ ГЛАВНОЕ СЕГОДНЯ",
        "news_1_title": "ФИФА официально представила расписание матчей ЧМ-2026 в США, Мексике и Канаде!",
        "news_1_desc": "Исторический матч открытия пройдет на знаменитом стадионе «Ацтека» в Мексике. Нью-Йорк/Нью-Джерси получил право провести финал.",
        "news_1_author": "От редакции • Время чтения: 5 мин",
        "news_detail_link": "Подробнее ➔",
        "news_2_title": "«Арсенал» разгромил «Челси» 5:0 на «Эмирейтс», совершив эффектный рывок в таблице",
        "news_2_desc": "Дубли Бена Уайта и Кая Хаверца помогли «канонирам» разгромить соседей по городу и отправить мощный сигнал «Ман Сити»...",
        "news_2_time": "1 час назад • Время чтения: 3 мин",
        "news_3_title": "Килиан Мбаппе согласился на предварительные условия перехода в «Реал Мадрид»",
        "news_3_desc": "Все личные условия согласованы. Французская суперзвезда перейдет на «Бернабеу» бесплатно с рекордным подписным бонусом...",
        "news_3_time": "3 часа назад • Время чтения: 4 мин",
        "news_4_title": "Безумный сценарий в полуфинале: «Реал Мадрид» совершил чудо-камбэк против «Баварии»",
        "news_4_desc": "Два быстрых гола Хоселу в добавленное время взорвали «Сантьяго Бернабеу», выведя «сливочных» в финал...",
        "news_4_time": "Вчера • Время чтения: 6 мин",
        "wc26_days_until": "Осталось %1$d дней до церемонии открытия",
        "wc26_starts_today": "⚽ СТАРТ СЕГОДНЯ!",
        "wc26_ongoing": "⚽ Чемпионат мира 2026 уже идет!",
        "wc26_groups": "ГРУППЫ",
        "wc26_teams": "КОМАНДЫ",
        "wc26_news": "НОВОСТИ",
        "wc26_opening_match": "Матч открытия • Тур 1",
        "wc26_azteca_stadium": "Стадион Ацтека, Мехико",
        "wc26_metlife_stadium": "Стадион МетЛайф, Нью-Йорк",
        "wc26_vs": "vs",
        "wc26_round_1_group_a": "Тур 1 • Группа А",
        "wc26_group_a": "ГРУППА A",
        "wc26_group_b": "ГРУППА B",
        "wc26_qualified_teams": "ВЫШЕДШИЕ КОМАНДЫ",
        "wc26_exclusive_news": "ЭКСКЛЮЗИВ",
        "wc26_exclusive_news_title": "Финал ЧМ-2026 с размахом пройдет в Нью-Йорке/Нью-Джерси!",
        "wc26_exclusive_news_desc": "ФИФА официально отдала права на проведение финала стадиону «МетЛайф» вместимостью более 82 500 мест на 19 июля 2026 года.",
        "wc26_preparation": "ПОДГОТОВКА",
        "wc26_prep_title": "США ускоряют модернизацию транспорта и безопасности в преддверии рекорда посещаемости",
        "wc26_prep_desc": "Федеральное правительство выделило специальный бюджет на обновление метро и авиасообщения между городами-организаторами...",
        "wc26_view_now": "СМОТРЕТЬ СЕЙЧАС ➔",
        "wc26_general_news": "📰 ОБЩИЕ НОВОСТИ",
        "wc26_general_news_desc": "Смотрите спортивные события, трансферы и новости лиг за последние 24 часа",
        "league_center_title": "ЦЕНТР ЛИГ",
        "league_center_subtitle": "Мировые таблицы и статистика",
        "tab_scorers": "БОМБАРДИРЫ",
        "tab_assists": "АССИСТЫ",
        "share_title": "ПОДЕЛИТЬСЯ МАТЧЕМ",
        "share_score_title": "Счет и статус",
        "share_score_desc": "Поделитесь голами в реальном времени и статусом матча.",
        "share_stats_title": "Подробная статистика",
        "share_stats_desc": "Поделитесь владением мячом, ударами и угловыми.",
        "share_full_title": "Полный отчет о матче",
        "share_full_desc": "Поделитесь полным отчетом, сочетающим счет и статистику.",
        "share_via": "Поделиться через",
        "share_copied_toast": "Скопировано в буфер обмена!",
        "reminder_set_toast": "Напоминание о матче включено!",
        "reminder_cancelled_toast": "Напоминание о матче выключено!",
        "share_caption_template": "Посмотрите статистику матча %1$s против %2$s на livescore://match/%3$d (Скачать приложение: https://livescore.premium/download)"
    },
    
    # Urdu (ur)
    "ur": {
        "app_name": "لائیو اسکور پریمیم",
        "nav_live": "براہ راست",
        "nav_news": "خبریں",
        "nav_favorite": "پسندیدہ",
        "nav_profile": "پروفائل",
        "wc26": "ورلڈ کپ 26",
        "favorite_title": "پسندیدہ",
        "my_follow": "آپ کے فالووز",
        "my_matches": "آپ کے میچز",
        "live": "براہ راست",
        "upcoming": "آنے والے",
        "finished": "ختم شدہ",
        "empty_matches": "ابھی تک کوئی پسندیدہ میچ نہیں ہے",
        "empty_leagues": "ابھی تک کوئی پسندیدہ لیگ نہیں ہے",
        "empty_teams": "ابھی تک کوئی پسندیدہ ٹیم نہیں ہے",
        "empty_players": "ابھی تک کوئی پسندیدہ کھلاڑی نہیں ہے",
        "profile_title": "میرا پروفائل",
        "language": "زبان",
        "premium_badge": "👑 پریمیم ممبر",
        "free_plan": "مفت پلان",
        "daily_limit": "روزانہ API کے استعمال کی حد",
        "upgrade_button": "ابھی اپ گریڈ کریں",
        "intro_next": "آگے",
        "intro_start": "شروع کریں",
        "intro_step_1_progress": "مرحلہ 1: 1/3",
        "intro_step_2_progress": "مرحلہ 2: 2/3",
        "intro_step_3_progress": "مرحلہ 3: 3/3",
        "intro_step_1_title": "پسندیدہ لیگز منتخب کریں",
        "intro_step_1_subtitle": "اپنی پسندیدہ لیگز کی خبریں اور نتائج فلٹر کریں",
        "intro_step_1_hint": "لیگز تلاش کریں...",
        "intro_step_2_title": "فالو کرنے والی ٹیمیں منتخب کریں",
        "intro_step_2_subtitle": "ہم آپ کے منتخب کردہ کلبوں کو ترجیح دیں گے",
        "intro_step_2_hint": "ٹیمیں، کلبز تلاش کریں...",
        "intro_step_3_title": "پسندیدہ کھلاڑی منتخب کریں",
        "intro_step_3_subtitle": "دنیا کے ٹاپ فٹ بال سپر اسٹارز کو فالو کریں",
        "intro_step_3_hint": "کھلاڑی تلاش کریں...",
        "intro_finish": "ختم کریں",
        "item_hot": " • مقبول 🔥",
        "item_belongs": "تعلق ہے: %1$s",
        "item_nationality": "قومیت: %1$s",
        "intro_skip": "چھوڑیں",
        "intro_no_results": "کوئی نتیجہ نہیں ملا",
        "welcome_title": "لائیو اسکور میں خوش آمدید",
        "choose_language": "زبان منتخب کریں",
        "choose_language_desc": "آگے بڑھنے کے لیے ایپ کی آفیشل ڈسپلے زبان منتخب کریں۔",
        "profile_settings": "ترتیبات",
        "profile_display_preferences": "ڈسپلے اور پرسنلائزیشن",
        "profile_system": "اسٹوریج اور سسٹم",
        "profile_about": "سافٹ ویئر کی معلومات",
        "profile_version": "ورژن",
        "language_dialog_title": "زبان منتخب کریں",
        "language_changed_toast": "زبان %1$s پر اپ ڈیٹ کر دی گئی ہے",
        "splash_app_title": "لائیو اسکور",
        "splash_subtitle": "پریمیم اسپورٹس ہب",
        "tab_matches": "میچز",
        "tab_leagues": "لیگز",
        "empty_fixtures": "کوئی میچ نہیں ملا",
        "tab_standings": "جدول",
        "tab_fixtures": "میچز",
        "table_header_team": "ٹیم",
        "table_header_p": "کھیلے",
        "table_header_w": "جیتے",
        "table_header_d": "ڈرا",
        "table_header_l": "ہارے",
        "table_header_gd": "فرق",
        "table_header_pts": "پوائنٹس",
        "tab_stats": "اعدادوشمار",
        "tab_timeline": "ٹائم لائن",
        "tab_lineups": "لائن اپ",
        "search_input_hint": "میچ، ٹیم، لیگ تلاش کریں...",
        "search_empty_title": "فٹ بال دریافت کریں",
        "search_empty_desc": "پریمیم لیگ، ریال میڈرڈ، پاکستان یا ورلڈ کپ 2026 جیسی ٹاپ ٹیمیں اور لیگز تلاش کریں...",
        "news_center_title": "24 گھنٹے کی خبریں",
        "news_featured_today": "⭐ آج کی خاص خبر",
        "news_1_title": "فیفا نے باضابطہ طور پر امریکہ، میکسیکو اور کینیڈا میں ہونے والے ورلڈ کپ 2026 کے شیڈول کا اعلان کر دیا!",
        "news_1_desc": "تاریخی افتتاحی میچ میکسیکو کے مشہور ازٹیکا اسٹیڈیم میں کھیلا جائے گا۔ نیویارک/نیو جرسی کو فائنل کی میزبانی ملی ہے۔",
        "news_1_author": "ادارتی بورڈ کی جانب سے • 5 منٹ کا مطالعہ",
        "news_detail_link": "تفصیل ➔",
        "news_2_title": "آرسنل نے ایمریٹس میں چیلسی کو 5-0 سے شکست دے کر ڈرامائی چھلانگ لگائی",
        "news_2_desc": "بین وائٹ اور کائی ہیورٹز کے دوہرے گولز نے گنرز کو اپنے حریفوں کو ہرانے میں مدد کی اور مین سٹی کو پیغام بھیجا...",
        "news_2_time": "1 گھنٹہ پہلے • 3 منٹ کا مطالعہ",
        "news_3_title": "کلیان ایمباپے نے ریال میڈرڈ میں شامل ہونے کے لیے ابتدائی شرائط پر اتفاق کر لیا",
        "news_3_desc": "تمام ذاتی شرائط پر اتفاق ہو گیا ہے۔ فرانسیسی سپر اسٹار ریکارڈ سائننگ بونس کے ساتھ فری ایجنٹ کے طور پر برنابیو پہنچیں گے...",
        "news_3_time": "3 گھنٹے پہلے • 4 منٹ کا مطالعہ",
        "news_4_title": "سیمی فائنل میں سنسنی خیز مقابلہ: ریال میڈرڈ نے بایرن میونخ کے خلاف معجزاتی واپسی کی",
        "news_4_desc": "انجری ٹائم میں جوزلو کے دو تیز گولز نے برنابیو کو گرما دیا، ریال میڈرڈ کو فائنل میں پہنچا دیا...",
        "news_4_time": "کل • 6 منٹ کا مطالعہ",
        "wc26_days_until": "افتتاحی تقریب میں %1$d دن باقی ہیں",
        "wc26_starts_today": "⚽ آغاز آج ہے!",
        "wc26_ongoing": "⚽ ورلڈ کپ 2026 جاری ہے!",
        "wc26_groups": "گروپس",
        "wc26_teams": "ٹیمیں",
        "wc26_news": "خبریں",
        "wc26_opening_match": "افتتاحی میچ • راؤنڈ 1",
        "wc26_azteca_stadium": "ازٹیکا اسٹیڈیم، میکسیکو سٹی",
        "wc26_metlife_stadium": "میٹ لائف اسٹیڈیم، نیویارک",
        "wc26_vs": "بمقابلہ",
        "wc26_round_1_group_a": "راؤنڈ 1 • گروپ اے",
        "wc26_group_a": "گروپ اے",
        "wc26_group_b": "گروپ بی",
        "wc26_qualified_teams": "کوالیفائی کرنے والی ٹیمیں",
        "wc26_exclusive_news": "خصوصی خبر",
        "wc26_exclusive_news_title": "ورلڈ کپ 2026 کا فائنل نیویارک/نیو جرسی میں شاندار طور پر منعقد کیا جائے گا!",
        "wc26_exclusive_news_desc": "فیفا نے باضابطہ طور پر 19 جولائی 2026 کو 82,500 سے زیادہ گنجائش والے میٹ لائف اسٹیڈیم کو فائنل کی میزبانی کا حق دیا۔",
        "wc26_preparation": "تیاریاں",
        "wc26_prep_title": "امریکہ نے ریکارڈ شائقین کے لیے ٹرانسپورٹ اور سیکورٹی کے بنیادی ڈھانچے کو تیز کر دیا",
        "wc26_prep_desc": "وفاقی حکومت نے میزبان شہروں کو براہ راست جوڑنے والے سب ویز اور ایوی ایشن کو اپ گریڈ کرنے کے لیے خصوصی بجٹ کی منظوری دی...",
        "wc26_view_now": "ابھی دیکھیں ➔",
        "wc26_general_news": "📰 عام خبریں",
        "wc26_general_news_desc": "پچھلے 24 گھنٹوں کے تمام کھیلوں کے مقابلے، ٹرانسفرز اور لیگ کی خبریں دیکھیں",
        "league_center_title": "لیگ سینٹر",
        "league_center_subtitle": "عالمی درجہ بندی اور اعدادوشمار",
        "tab_scorers": "اسکوررز",
        "tab_assists": "اسسٹس",
        "share_title": "میچ شیئر کریں",
        "share_score_title": "اسکور اور صورتحال",
        "share_score_desc": "ریئل ٹائم گولز اور میچ کی صورتحال شیئر کریں۔",
        "share_stats_title": "تفصیلی میچ کے اعدادوشمار",
        "share_stats_desc": "بال پوزیشن، شاٹس، اور کارنر ککس شیئر کریں۔",
        "share_full_title": "مکمل میچ رپورٹ",
        "share_full_desc": "اسکور اور اعدادوشمار پر مشتمل مکمل رپورٹ شیئر کریں۔",
        "share_via": "کے ذریعے شیئر کریں",
        "share_copied_toast": "کلپ بورڈ پر کاپی ہو گیا!",
        "reminder_set_toast": "میچ کے لیے یاددہانی فعال ہو گئی!",
        "reminder_cancelled_toast": "میچ کے لیے یاددہانی غیر فعال ہو گئی!",
        "share_caption_template": "livescore://match/%3$d پر %1$s بمقابلہ %2$s کے میچ کے اعدادوشمار دیکھیں (ایپ ڈاؤن لوڈ کریں: https://livescore.premium/download)"
    }
}

# Base XML layout template
xml_template = """<?xml version="1.0" encoding="utf-8"?>
<resources>
{items}
</resources>
"""

# Write localized files to output folders
res_root = "c:/csc-project/livescore/app/src/main/res"

for lang, data in translations.items():
    lang_dir = os.path.join(res_root, f"values-{lang}")
    os.makedirs(lang_dir, exist_ok=True)
    
    xml_items = []
    for key, value in data.items():
        # Escape string values for XML compatibility
        escaped_value = value.replace("'", "\\'").replace("&", "&amp;").replace('"', '\\"')
        xml_items.append(f'    <string name="{key}">{escaped_value}</string>')
        
    xml_content = xml_template.format(items="\n".join(xml_items))
    
    output_path = os.path.join(lang_dir, "strings.xml")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(xml_content)
        
    print(f"Generated successfully: {output_path}")
